version: '3.8'

services:
  # PostgreSQL Database for development
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: tourtinder
      POSTGRES_PASSWORD: tourtinder123
      POSTGRES_DB: tourtinder
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tourtinder"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis Cache for development
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Adminer - Database UI
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  # Redis Commander - Redis UI
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

  # Bull Dashboard - Queue monitoring
  bull-board:
    image: deadly0/bull-board
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3333:3000"
    depends_on:
      - redis

volumes:
  postgres_dev_data:
  redis_dev_data: