version: '3.8'

# This file demonstrates how to use Docker Secrets in production
# Usage: docker-compose -f docker-compose.yml -f docker-compose.secrets.yml up

services:
  app:
    secrets:
      - telegram_token
      - openrouter_api_key
      - leveltravel_api_key
      - session_secret
      - jwt_secret
      - csrf_secret
    environment:
      # Override environment variables to read from secrets
      TELEGRAM_TOKEN_FILE: /run/secrets/telegram_token
      OPENROUTER_API_KEY_FILE: /run/secrets/openrouter_api_key
      LEVELTRAVEL_API_KEY_FILE: /run/secrets/leveltravel_api_key
      SESSION_SECRET_FILE: /run/secrets/session_secret
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      CSRF_SECRET_FILE: /run/secrets/csrf_secret

secrets:
  telegram_token:
    external: true
  openrouter_api_key:
    external: true
  leveltravel_api_key:
    external: true
  session_secret:
    external: true
  jwt_secret:
    external: true
  csrf_secret:
    external: true

# To create secrets in Docker Swarm:
# echo "your-telegram-token" | docker secret create telegram_token -
# echo "your-openrouter-key" | docker secret create openrouter_api_key -
# echo "your-leveltravel-key" | docker secret create leveltravel_api_key -
# openssl rand -hex 32 | docker secret create session_secret -
# openssl rand -hex 32 | docker secret create jwt_secret -
# openssl rand -hex 32 | docker secret create csrf_secret -